name: bridges
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - matplotlib=3.7
  - seaborn
  - plotly
  - scikit-learn
  - geopandas
  - shap
  - jupyter
  - ipykernel
  - dash
  - pip
  - pip:
      - tueplots
      - kaleido
      - -e ./pybeeswarm
